[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rsg-phot"
version = "0.1"
description = "A Python package for red supergiant photometry analysis"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "Aswin Suresh", email = "aswinsuresh4869@gmail.com"}
]

dependencies = [
    "numpy",
    "pandas",
    "astropy",
    "matplotlib",
    "tqdm",
    "dustmaps",
    "dust-extinction",
    "sbi",
    "torch",
    "emcee",
    "progressbar2",
    "synphot",
    "scipy",
    "corner",
    "trackio"
]

[project.urls]
Homepage = "https://github.com/aswinsuresh24/rsg_phot"

[tool.setuptools]
packages = ["rsg_phot"]